apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o85h619vb-go 
  janus-idp.io/tekton: o85h619vb-go
  backstage.io/kubernetes-id: o85h619vb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o85h619vb-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml